### ISSUE TITLE
Idea for a loader

### ISSUE THREAD

**Issue by cycomachead** [beautyjoy/llab#156]
http://wise.berkeley.edu/vle/util/scriptloader.js

**Comment by xtitter** [comment]
That wise solution was always kinda a hack, though.  What's wrong with
require.js?

It'd be nice to have scripts that could work in node or the browser...
Isn't require.js the same been the two?

- nate (tiny phone, fat thumbs)

**Comment by xtitter** [comment]
I was just working on this one!!  Lol, no I wasn't.
